version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      vivisect: # You can name this whatever you like
        patterns:
          - "vivisect"
          - "pyasn1"
          - "pyasn1-modules"
          - "msgpack"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
