version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pyasn1-updates:
        patterns:
          - "pyasn1"
          - "pyasn1-modules"
          - "vivisect"
      msgpack-updates:
        patterns:
          - "msgpack"
          - "vivisect"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
